USE [master]
GO

/****** Object:  Database [hastabilgi]    Script Date: 7.06.2020 15:09:24 ******/
CREATE DATABASE [hastabilgi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hastabilgi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\hastabilgi.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'hastabilgi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\hastabilgi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hastabilgi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hastabilgi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hastabilgi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hastabilgi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hastabilgi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hastabilgi] SET ARITHABORT OFF 
GO

ALTER DATABASE [hastabilgi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hastabilgi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hastabilgi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hastabilgi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hastabilgi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hastabilgi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hastabilgi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hastabilgi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hastabilgi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hastabilgi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hastabilgi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hastabilgi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hastabilgi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hastabilgi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hastabilgi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hastabilgi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hastabilgi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hastabilgi] SET RECOVERY FULL 
GO

ALTER DATABASE [hastabilgi] SET  MULTI_USER 
GO

ALTER DATABASE [hastabilgi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hastabilgi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [hastabilgi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [hastabilgi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [hastabilgi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [hastabilgi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [hastabilgi] SET  READ_WRITE 
GO

